export const ports: DataType[] = [
    {key: 0, name: 'VOSTOCHNY (Восточный)'},
    {key: 1, name: 'VLADIVOSTOK (ВМТП)'},
    {key: 2, name: 'FISH PORT (ВМКТ)'},
]

export interface ExpandedDataType {
    key: number
    city: string
    Torgmoll?: string
    Sinokor?: string
    Fesco?: string
    Sasco?: string
    Torgmoll40?: string
    Sinokor40?: string
    Fesco40?: string
    MAS?: string
    Sasco40?: string
    Gangtong?: string
    OVP?: string
    GFL?: string
    SITC?: string
    Gangtong40?: string
    OVP40?: string
    GFL40?: string
    SITC40?: string
    RusTransGroup?: string
    SCO?: string
    HUB?: string
    DVLK?: string
    RusTransGroup40?: string
    SCO40?: string
    HUB40?: string
    DVLK40?: string
}

export interface DataType {
    key: string | number;
    name: string;
}

export const columnsVostochniy = [
    {title: 'Порт отправления', dataIndex: 'city', key: 'city'},
    {title: '20\'DC/Torgmoll', dataIndex: 'Torgmoll', key: 'Torgmoll'},
    {title: '20\'DC/Sinokor', dataIndex: 'Sinokor', key: 'Sinokor'},
    {title: '20\'DC/Fesco', dataIndex: 'Fesco', key: 'Fesco'},
    {title: '20\'DC/Sasco', dataIndex: 'Sasco', key: 'Sasco'},
    {title: '40\'HC/Torgmoll', dataIndex: 'Torgmoll40', key: 'Torgmoll40'},
    {title: '40\'HC/Sinokor', dataIndex: 'Sinokor40', key: 'Sinokor40'},
    {title: '40\'HC/Fesco', dataIndex: 'Fesco40', key: 'Fesco40'},
    {title: '40\'HC/MAS', dataIndex: 'MAS', key: 'MAS'},
    {title: '40\'HC/Sasco', dataIndex: 'Sasco40', key: 'Sasco40'},
]
export const pricesVostochniy: ExpandedDataType[] = [
    {
        key: 0,
        city: 'Shanghai',
        Torgmoll: '$3 700',
        Sinokor: '$5 000',
        Fesco: '$4 960',
        Sasco: '$3 760',
        Torgmoll40: '$5 400',
        Sinokor40: '$7 160',
        Fesco40: '$6 260',
        MAS: '$4 910',
        Sasco40: '$5 110'
    },
    {
        key: 1,
        city: 'Ningbo',
        Torgmoll: '',
        Sinokor: '$5 000',
        Fesco: '$4 960',
        Sasco: '$3 760',
        Torgmoll40: '',
        Sinokor40: '$7 160',
        Fesco40: '$6 360',
        MAS: '$5 010',
        Sasco40: '$5 210',
    },
    {
        key: 2,
        city: 'Qingdao',
        Torgmoll: '$3 700',
        Sinokor: '$5 000',
        Fesco: '$5 160',
        Sasco: '$4 110',
        Torgmoll40: '$5 500',
        Sinokor40: '$7 160',
        Fesco40: '$6 760',
        MAS: '$5 210',
        Sasco40: '$5 710',
    },
    {
        key: 3,
        city: 'Xiamen',
        Torgmoll: '$3 800',
        Sinokor: '$5 000',
        Fesco: '$5 060',
        Sasco: '',
        Torgmoll40: '$5 810',
        Sinokor40: '$7 160',
        Fesco40: '$7 160',
        MAS: '$5 410',
        Sasco40: '',
    },
    {
        key: 4,
        city: 'Huangpu',
        Torgmoll: '$3 910',
        Sinokor: '$5 000',
        Fesco: '$5 310',
        Sasco: '',
        Torgmoll40: '$5 710',
        Sinokor40: '$7 160',
        Fesco40: '$7 560',
        MAS: '$5 410',
        Sasco40: '',
    },
    {
        key: 5,
        city: 'Yantian',
        Torgmoll: '$3 910',
        Sinokor: '',
        Fesco: '$5 060',
        Sasco: '',
        Torgmoll40: '$5 710',
        Sinokor40: '',
        Fesco40: '$7 060',
        MAS: '$5 310',
        Sasco40: '',
    },
    {
        key: 6,
        city: 'Dalian',
        Torgmoll: '',
        Sinokor: '$5 000',
        Fesco: '$5 810',
        Sasco: '',
        Torgmoll40: '$5 800',
        Sinokor40: '$7 160',
        Fesco40: '$6 960',
        MAS: '$5 210',
        Sasco40: '',
    },
    {
        key: 7,
        city: 'Xingang',
        Torgmoll: '$3 600',
        Sinokor: '$5 000',
        Fesco: '$4 960',
        Sasco: '',
        Torgmoll40: '$5 300',
        Sinokor40: '$7 160',
        Fesco40: '$6 410',
        MAS: '$5 360',
        Sasco40: '',
    },
    {
        key: 8,
        city: 'Busan',
        Torgmoll: '$3 900',
        Sinokor: '$5 000',
        Fesco: '$3 510',
        Sasco: '',
        Torgmoll40: '$5 810',
        Sinokor40: '$6 360',
        Fesco40: '$4 910',
        MAS: '',
        Sasco40: '',
    },
    {
        key: 9,
        city: 'Shantou',
        Torgmoll: '$5 000',
        Sinokor: '',
        Fesco: '$5 910',
        Sasco: '',
        Torgmoll40: '',
        Sinokor40: '$7 160',
        Fesco40: '$7 660',
        MAS: '',
        Sasco40: '',
    },
    {
        key: 10,
        city: 'Shekou',
        Torgmoll: '$5 000',
        Sinokor: '',
        Fesco: '',
        Sasco: '',
        Torgmoll40: '',
        Sinokor40: '$7 160',
        Fesco40: '',
        MAS: '',
        Sasco40: '',
    },
    {
        key: 11,
        city: 'Taicang',
        Torgmoll: '',
        Sinokor: '',
        Fesco: '$5 810',
        Sasco: '',
        Torgmoll40: '',
        Sinokor40: '',
        Fesco40: '$7 260',
        MAS: '$4 910',
        Sasco40: '',
    },
    {
        key: 12,
        city: 'Zhapu',
        Torgmoll: '',
        Sinokor: '',
        Fesco: '$5 160',
        Sasco: '',
        Torgmoll40: '',
        Sinokor40: '',
        Fesco40: '$6 460',
        MAS: '',
        Sasco40: '',
    },
    {
        key: 14,
        city: 'Nansha',
        Torgmoll: '',
        Sinokor: '$5 200',
        Fesco: '',
        Sasco: '',
        Torgmoll40: '',
        Sinokor40: '$7 360',
        Fesco40: '',
        MAS: '$5 310',
        Sasco40: '',
    },
    {
        key: 15,
        city: 'Rizhao',
        Torgmoll: '$3 900',
        Sinokor: '',
        Fesco: '$5 260',
        Sasco: '',
        Torgmoll40: '$5 510',
        Sinokor40: '',
        Fesco40: '$6 460',
        MAS: '$5 310',
        Sasco40: ''
    },
]

export const columnsVladivostok = [
    {title: 'Порт отправления', dataIndex: 'city', key: 'city'},
    {title: '20\'DC/Gangtong', dataIndex: 'Gangtong', key: 'Gangtong'},
    // {title: '20\'DC/OVP', dataIndex: 'OVP', key: 'OVP'},
    {title: '20\'DC/Sinokor', dataIndex: 'Sinokor', key: 'Sinokor'},
    {title: '20\'DC/GFL', dataIndex: 'GFL', key: 'GFL'},
    {title: '20\'DC/Fesco', dataIndex: 'Fesco', key: 'Fesco'},
    // {title: '20\'DC/SITC', dataIndex: 'SITC', key: 'SITC'},

    {title: '40\'HC/Gangtong', dataIndex: 'Gangtong40', key: 'Gangtong40'},
    // {title: '40\'HC/OVP', dataIndex: 'OVP40', key: 'OVP40'},
    {title: '40\'HC/Sinokor', dataIndex: 'Sinokor40', key: 'Sinokor40'},
    {title: '40\'HC/GFL', dataIndex: 'GFL40', key: 'GFL40'},
    {title: '40\'HC/Fesco', dataIndex: 'Fesco40', key: 'Fesco40'},
    // {title: '40\'HC/SITC', dataIndex: 'SITC40', key: 'SITC40'},
]
export const pricesVladivostok: ExpandedDataType[] = [
    {
        key: 0,
        city: 'Shanghai',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '$4 110',
        Fesco: '$4 960',
        SITC: '$3 200',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '$5 610',
        Fesco40: '$6 260',
        SITC40: '$4 900',
    },
    {
        key: 1,
        city: 'Ningbo',
        Gangtong: '$3 446',
        OVP: '$3 446',
        Sinokor: '$5 000',
        GFL: '$3 710',
        Fesco: '$4 960',
        SITC: '',
        Gangtong40: '$5 032',
        OVP40: '$5 182',
        Sinokor40: '$7 160',
        GFL40: '$5 110',
        Fesco40: '$6 360',
        SITC40: '',
    },
    {
        key: 2,
        city: 'Qingdao',
        Gangtong: '$3 446',
        OVP: '$3 346',
        Sinokor: '$5 000',
        GFL: '',
        Fesco: '$5 160',
        SITC: '',
        Gangtong40: '$4 782',
        OVP40: '$4 882',
        Sinokor40: '$7 160',
        GFL40: '',
        Fesco40: '$6 760',
        SITC40: '',
    },
    {
        key: 3,
        city: 'Xiamen',
        Gangtong: '$3 846',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '$4 510',
        Fesco: '$5 060',
        SITC: '',
        Gangtong40: '$5 832',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '$6 210',
        Fesco40: '$7 160',
        SITC40: '',
    },
    {
        key: 4,
        city: 'Huangpu',
        Gangtong: '$3 846',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '',
        Fesco: '$5 310',
        SITC: '',
        Gangtong40: '$5 732',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '',
        Fesco40: '$7 560',
        SITC40: '',
    },
    {
        key: 5,
        city: 'Yantian',
        Gangtong: '$3 846',
        OVP: '',
        Sinokor: '',
        GFL: '$4 510',
        Fesco: '$5 060',
        SITC: '',
        Gangtong40: '$5 732',
        OVP40: '',
        Sinokor40: '',
        GFL40: '$6 210',
        Fesco40: '$7 060',
        SITC40: '',
    },
    {
        key: 6,
        city: 'Dalian',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '',
        Fesco: '$5 810',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '',
        Fesco40: '$6 960',
        SITC40: '',
    },
    {
        key: 7,
        city: 'Xingang',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '$4 510',
        Fesco: '$4 960',
        SITC: '$3 710',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '$6 210',
        Fesco40: '$6 410',
        SITC40: '$5 160',
    },
    {
        key: 8,
        city: 'Busan',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '',
        Fesco: '$3 510',
        SITC: '$4 110',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$6 360',
        GFL40: '',
        Fesco40: '$4 910',
        SITC40: '$5 710',
    },
    {
        key: 9,
        city: 'Shantou',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '',
        Fesco: '$5 910',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '',
        Fesco40: '$7 660',
        SITC40: '',
    },
    {
        key: 10,
        city: 'Shekou',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 000',
        GFL: '$4 510',
        Fesco: '',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$7 160',
        GFL40: '$6 210',
        Fesco40: '',
        SITC40: '',
    },
    {
        key: 11,
        city: 'Taicang',
        Gangtong: '',
        OVP: '',
        Sinokor: '',
        GFL: '$3 710',
        Fesco: '$5 810',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '',
        GFL40: '$5 210',
        Fesco40: '$7 260',
        SITC40: '',
    },
    {
        key: 12,
        city: 'Zhapu',
        Gangtong: '',
        OVP: '',
        Sinokor: '',
        GFL: '',
        Fesco: '$5 160',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '',
        GFL40: '',
        Fesco40: '$6 460',
        SITC40: '',
    },
    {
        key: 13,
        city: 'Nansha',
        Gangtong: '',
        OVP: '',
        Sinokor: '$5 200',
        GFL: '$4 510',
        Fesco: '',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '$7 360',
        GFL40: '$6 210',
        Fesco40: '',
        SITC40: '',
    },
    {
        key: 14,
        city: 'Rizhao',
        Gangtong: '',
        OVP: '',
        Sinokor: '',
        GFL: '$3 710',
        Fesco: '$5 260',
        SITC: '',
        Gangtong40: '',
        OVP40: '',
        Sinokor40: '',
        GFL40: '$5 110',
        Fesco40: '$6 460',
        SITC40: '',
    },
]

export const columnsFishport = [
    {title: 'Порт отправления', dataIndex: 'city', key: 'city'},
    {title: '20\'DC/RusTransGroup', dataIndex: 'RusTransGroup', key: 'RusTransGroup'},
    {title: '20\'DC/Sinokor', dataIndex: 'Sinokor', key: 'Sinokor'},
    {title: '20\'DC/SCO', dataIndex: 'SCO', key: 'SCO'},
    // {title: '20\'DC/HUB', dataIndex: 'HUB', key: 'HUB'},
    {title: '20\'DC/ДВЛК', dataIndex: 'DVLK', key: 'DVLK'},
    // {title: '20\'DC/Sasco', dataIndex: 'Sasco', key: 'Sasco'},

    {title: '40\'HC/RusTransGroup', dataIndex: 'RusTransGroup40', key: 'RusTransGroup40'},
    {title: '40\'HC/Sinokor', dataIndex: 'Sinokor40', key: 'Sinokor40'},
    {title: '40\'HC/SCO', dataIndex: 'SCO40', key: 'SCO40'},
    // {title: '40\'HC/HUB', dataIndex: 'HUB40', key: 'HUB40'},
    {title: '40\'HC/ДВЛК', dataIndex: 'DVLK40', key: 'DVLK40'},
    // {title: '40\'HC/Sasco', dataIndex: 'Sasco40', key: 'Sasco40'},

]

export const pricesFishport: ExpandedDataType[] = [
    {
        key: 0,
        city: 'Shanghai',
        RusTransGroup: '$3 610',
        Sinokor: '$5 000',
        SCO: '$3 250',
        DVLK: '',
        RusTransGroup40: '$5 110',
        Sinokor40: '$7 160',
        SCO40: '$4 600',
        DVLK40: '',
    },
    {
        key: 1,
        city: 'Ningbo',
        RusTransGroup: '$3 450',
        Sinokor: '$5 000',
        SCO: '$3 250',
        DVLK: '$3 310',
        RusTransGroup40: '$4 950',
        Sinokor40: '$7 160',
        SCO40: '$4 600',
        DVLK40: '$4 610',
    },
    {
        key: 2,
        city: 'Qingdao',
        RusTransGroup: '$3 550',
        Sinokor: '$5 000',
        SCO: '',
        DVLK: '$3 430',
        RusTransGroup40: '$5 100',
        Sinokor40: '$7 160',
        SCO40: '',
        DVLK40: '$4 785',
    },
    {
        key: 3,
        city: 'Xiamen',
        RusTransGroup: '$3 810',
        Sinokor: '$5 000',
        SCO: '$3 560',
        DVLK: '',
        RusTransGroup40: '$5 600',
        Sinokor40: '$7 160',
        SCO40: '$5 300',
        DVLK40: '',
    },
    {
        key: 4,
        city: 'Huangpu',
        RusTransGroup: '',
        Sinokor: '$5 000',
        SCO: '$3 800',
        DVLK: '',
        RusTransGroup40: '',
        Sinokor40: '$7 160',
        SCO40: '$5 410',
        DVLK40: '',
    },
    {
        key: 5,
        city: 'Yantian',
        RusTransGroup: '$4 110',
        Sinokor: '',
        SCO: '$3 760',
        DVLK: '',
        RusTransGroup40: '$6 050',
        Sinokor40: '',
        SCO40: '$5 600',
        DVLK40: '',
    },
    {
        key: 6,
        city: 'Dalian',
        RusTransGroup: '$4 010',
        Sinokor: '$5 000',
        SCO: '$3 660',
        DVLK: '',
        RusTransGroup40: '$6 060',
        Sinokor40: '$7 160',
        SCO40: '$5 410',
        DVLK40: '',
    },
    {
        key: 7,
        city: 'Xingang',
        RusTransGroup: '$3 850',
        Sinokor: '$5 000',
        SCO: '$3 660',
        DVLK: '',
        RusTransGroup40: '$5 550',
        Sinokor40: '$7 160',
        SCO40: '$5 260',
        DVLK40: '',
    },
    // {
    //     key: 8,
    //     city: 'Busan',
    //     RusTransGroup: '',
    //     Sinokor: '$5 000',
    //     SCO: '',
    //     DVLK: '',
    //     RusTransGroup40: '',
    //     Sinokor40: '',
    //     SCO40: '',
    //     DVLK40: '',
    // },
    {
        key: 9,
        city: 'Shantou',
        RusTransGroup: '$4 190',
        Sinokor: '$5 000',
        SCO: '$3 860',
        DVLK: '',
        RusTransGroup40: '$6 040',
        Sinokor40: '$7 160',
        SCO40: '$5 510',
        DVLK40: '',
    },
    {
        key: 10,
        city: 'Shekou',
        RusTransGroup: '$4 299',
        Sinokor: '$5 000',
        SCO: '$3 760',
        DVLK: '',
        RusTransGroup40: '$6 050',
        Sinokor40: '$7 160',
        SCO40: '$5 410',
        DVLK40: '',
    },
    {
        key: 11,
        city: 'Taicang',
        RusTransGroup: '$3 900',
        Sinokor: '',
        SCO: '',
        DVLK: '$3 710',
        RusTransGroup40: '$5 410',
        Sinokor40: '',
        SCO40: '',
        DVLK40: '$4 610',
    },
    // {
    //     key: 12,
    //     city: 'Zhapu',
    //     RusTransGroup: '$3 660',
    //     Sinokor: '',
    //     SCO: '',
    //     DVLK: '',
    //     RusTransGroup40: '$5 210',
    //     Sinokor40: '',
    //     SCO40: '',
    //     DVLK40: '',
    // },
    // {
    //     key: 13,
    //     city: 'Humen',
    //     RusTransGroup: '',
    //     Sinokor: '',
    //     SCO: '',
    //     DVLK: '',
    //     RusTransGroup40: '',
    //     Sinokor40: '',
    //     SCO40: '',
    //     DVLK40: '',
    // },
    {
        key: 14,
        city: 'Nansha',
        RusTransGroup: '$4 310',
        Sinokor: '$5 200',
        SCO: '$3 760',
        DVLK: '$4 310',
        RusTransGroup40: '$6 210',
        Sinokor40: '$7 360',
        SCO40: '$5 410',
        DVLK40: '$5 710',
    },
    {
        key: 15,
        city: 'Rizhao',
        RusTransGroup: '',
        Sinokor: '',
        SCO: '$3 360',
        DVLK: '$3 310',
        RusTransGroup40: '',
        Sinokor40: '',
        SCO40: '$4 560',
        DVLK40: '$4 610',
    },
]
